# 배포용 (데스크탑, 서와실)
# docker-compose -f docker-compose.yml up -d
version: '3.8'

services:
  frontend:
    container_name: seowasil-frontend
    build:
      context: .
      dockerfile: Dockerfile # local 개발용 Dockerfile을 사용
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    command: npm run start
    networks:
      - backbone

  nginx:
    container_name: nginx
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./dev/default/nginx.conf:/etc/nginx/nginx.conf
      - ./dev/nginx:/etc/nginx/conf.d
      - /letsencrypt/certbot/conf:/etc/letsencrypt
      - /letsencrypt/certbot/www:/var/www/certbot
    depends_on:
      - frontend
    networks:
      - backbone
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''

  certbot:
    container_name: certbot
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - /letsencrypt/certbot/conf:/etc/letsencrypt
      - /letsencrypt/certbot/www:/var/www/certbot
    depends_on:
      - nginx
    networks:
      - backbone
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  backbone:
    driver: bridge
