version: '3.8'

services:
  frontend:
    container_name: seowasil-frontend
    build:
      context: .
      dockerfile: Dockerfile.local # local 개발용 Dockerfile을 사용
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
    command: npm run start:dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
