# 찐 개발용
version: '3.8'

services:
  seowasil_client_local:
    container_name: seowasil_client_local
    build:
      context: .
      dockerfile: Dockerfile.local
    environment:
      NODE_ENV: development
    ports:
      - '3000:3000'
    command: npm run dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules