import { ReduxProviders } from '@/lib/redux/ReduxProvider';
import type { Metadata } from 'next';
import TanStackProviders from '@/lib/react-query/QueryProvider';
import StyledComponentsRegistry from '@/lib/styled-components/registry';
import MuiProvier from '@/lib/mui/MuiProvier';
import Container from '@mui/material/Container';
import Box from '@mui/material/Box';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ko-kr">
      <body>
        <ReduxProviders>
          <TanStackProviders>
            <StyledComponentsRegistry>
              <MuiProvier options={{ key: 'mui' }}>
                <Container maxWidth="xl">
                  <Box
                    sx={{
                      marginTop: 2,
                      bgcolor: '#cfe8fc',
                      height: '100vh',
                    }}
                  >
                    <div>
                      <Link href="/">메인 페이지로 이동</Link>
                    </div>
                    {children}
                  </Box>
                </Container>
              </MuiProvier>
            </StyledComponentsRegistry>
          </TanStackProviders>
        </ReduxProviders>
      </body>
    </html>
  );
}
