import { ReduxProviders } from '@/lib/redux/ReduxProvider';
import type { Metadata } from 'next';
import TanStackProviders from '@/lib/react-query/QueryProvider';
import StyledComponentsRegistry from '@/lib/styled-components/registry';
import MuiProvier from '@/lib/mui/MuiProvier';
import Container from '@mui/material/Container';
import Header from '@/components/Header';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ko-kr">
      <body>
        <ReduxProviders>
          <TanStackProviders>
            <StyledComponentsRegistry>
              <MuiProvier options={{ key: 'mui' }}>
                <Container maxWidth="xl">
                  <Header />
                  {children}
                </Container>
              </MuiProvier>
            </StyledComponentsRegistry>
          </TanStackProviders>
        </ReduxProviders>
      </body>
    </html>
  );
}
